image/scripts/sample.toml
src/Server.jl
src/register.jl

Pass additional git configuration flags, primarily to set user context for requests.
So that, Registrator.jl doesn't depend on a git configuration file to exist. Even if one is present, it would use the identity configured with registrator instead.

pass additional git configuration flags

---

src/register.jl
test/runtests.jl

Fixes #52 
Adds a new `write_registry` function. I'm not a huge fan of having this specific-purpose function here and not in Pkg, but as long as the Pkg version is tied to the Julia version stuff like this will be necessary to allow people on older versions to use Registrator.

Make new registry entry for new package

---

image/Dockerfile
image/scripts/sample.toml
src/Server.jl

@nkottary As discussed in #39, this PR implements the Server getting its port from `ENV["PORT"]` if `http_port` is not set in the config.toml. If neither is set, then the server will use a default port of 8001.
This is useful for deploying places where you don't control the port number you get, like Heroku, which sets a value for `$PORT` when the app spins up.

Allow setting http_port through `$PORT`

---

image/scripts/sample.toml
src/Server.jl

This PR adds an option to the config:
```
[registrator]
registry_deps = ["https://github.com/JuliaRegistries/General"]
```
That can be extended to add more registries that can be used for dependency checking. This is for situations where you are registering a package to your registry, which has a dependency in a different registry. Which might be frequently for non-General registries: It's likely non-General registries will have packages that have dependencies in General).
By default, General is already listed there in the sample config.

Make the server use the registry_deps option when calling the `register` function

---

src/Server.jl

See #70 
- make clear that the tag should be made after the merge
- only pushed the new tag instead of all of the tags

Make clear that the tag should be made after merge

---

src/Server.jl

Instead of putting the warning message as a separate comment which may confuse users.

Make warning message part of reply comment

---

Manifest.toml
Project.toml
src/Registrator.jl
src/regedit/RegEdit.jl
src/regedit/register.jl
src/regedit/types.jl
src/regedit/utils.jl
test/regedit.jl

This starts the process of testing `register` by testing `get_registry`. 
Introduces RegistryCache for a non-global version of `REGISTRIES` (useful for testing and defining an API). 
Documents `register`. 
Introduces RegistryData for a data structure that represents a Registry.toml's data. Differentiates between operations on the data and reading/writing the data from a file.
We're at about 11% coverage for the package.

Test registry data access and get_registry

---

Manifest.toml
Project.toml
src/Registrator.jl
src/regedit/RegEdit.jl
src/regedit/register.jl
src/regedit/utils.jl

- Only include `name`, `uuid` and `repo` in `Package.toml`, and sort them in the same order as `Pkg` sorts in `Project.toml`, fixes #51.
- Remove use of `OrderedDict` and thus unnecessary `DataStructures` dependency, at least I could not find any other use of `DataStructures`...)
- Remove unused `write_toml` function.

Misc TOML writing changes

---

Manifest.toml
Project.toml
src/Registrator.jl
src/regedit/RegEdit.jl
src/regedit/register.jl
src/regedit/utils.jl

Fixes https://github.com/JuliaComputing/Registrator.jl/pull/92#issuecomment-484609860 by printing the dict directly. Demo to show that it actually works this time :tada: 
```
julia> versions_file = "/home/fredrik/.julia/registries/General/L/Literate/Versions.toml";
shell> cat $versions_file
["0.1.0"]
git-tree-sha1 = "710421f148e853a2dec017e98af48c4eafa4f2a8"
[...]
["1.1.0"]
git-tree-sha1 = "021e2e3106713e22a7f3769ebf9f2f4469670444"
julia> versions_data = isfile(versions_file) ? TOML.parsefile(versions_file) : Dict();
julia> versions_data = isfile(versions_file) ? TOML.parsefile(versions_file) : Dict();
julia> open(versions_file, "w") do io
TOML.print(io, versions_data; sorted=true, by=x->VersionNumber(x))
end;
shell> cat $versions_file
["0.1.0"]
git-tree-sha1 = …
```

Misc TOML writing changes, take 2

---

src/regedit/register.jl

Those functions does not belong in Base IMO, so better not use them and we can remove them from there (https://github.com/JuliaLang/julia/compare/cb85f840a533f79741b79dfd94a00d9581f22983..2e0d6b75356f101ee7f743bbb74cf7d6ce4f8a79)

Remove use of some Base functions in check_version.

---

src/Server.jl
src/regedit/register.jl

First commit enables a `metadata` dict in `RegBranch` instead of adding more fields, second commit adds the label functionality.

Add labels to PRs

---

src/Server.jl

Instead of looping over *all* pull requests, we can tell GitHub which one we want by specifying the head and base branches. There cannot be multiple open PRs with identical head and base branches, so we get at most one result.
Also did a quick find and replace over the file to "properly" compare to `nothing`.

More efficient lookup for existing pull request

---

src/Server.jl

An update to mention TagBot:
----
Registration pull request $msg: [$(repo)/$(pr.number)]($(pr.html_url))
After the above pull request is merged, it is recommended that a tag is created on this repository for the registered package version.
This will be done automatically if [Julia TagBot](https://github.com/apps/julia-tagbot) is installed, or can be done manually through the github interface or via:
```
git tag -a v$(string(ver)) -m "<description of version>" $(pp.sha)
git push origin v$(string(ver))
```
---
Perhaps the message could be shorter? or could Registrator check for TagBot installation?

Mention TagBot in registration notice

---

README.md
docs.md
image/scripts/sample.toml
src/Server.jl

This should fix the inability of *Members* (as opposed to *Owners*) of org-owned repos to invoke `@JuliaRegistrator`, even if they have release rights.
Designed to handle both repos owned by organizations through membership, and previous method for collaborators on privately owned repos
**N.B.** I haven't tested this code locally, as I was unsure how to on my local machine

Enable organizational membership check for release rights

---

src/regedit/register.jl

There were cases where version ranges like `["0.6", "0.7"]` weren't getting combined into a single range; this is a silly fix but round tripping through `VersionSpec` which combines these fixes that.

add line to combine joinable ranges

---

README.md
README.web.md
image/Dockerfile
image/scripts/sample.toml
src/WebUI.jl
test/runtests.jl
test/webui.jl

Turns out we should use repositories that we know will continue to exist as test examples :upside_down_face:. 
A bit of relevant discussion in #131.

Fix failing web test, update repo links

---

.gitignore
Manifest.toml
Project.toml
README.web.md
config.web.toml
src/Server.jl
src/WebUI.jl
src/pull_request.jl
src/regedit/register.jl
src/regedit/types.jl
test/webui.jl

On top of #149, only commits including and after f98019571ffa024f10f46bdb5174fd25b1981884 are new.
This gives the web UI its own configuration file, without touching the existing GItHub bot's file.
Kind of WIP but as far as I can tell it's working identically to before.

WebUI: Use a TOML configuration file instead of environment variables

---

src/Server.jl
src/pull_request.jl

I thought this was going to be the branch of the package repo being released, but it's not. It's not necessary anyways.

Don't include git ref in PRs from GitHub app

---

Manifest.toml
README.md
src/Server.jl

I'd expect plenty of people to use "Patch Notes:", etc.

Make patch notes capture case-insensitive

---

src/webui/gitutils.jl

Needs: https://github.com/christopher-dG/GitForge.jl/pull/6

WebUI: Check for existing PR and update

---

README.md
run/config.commentbot.toml
src/commentbot/CommentBot.jl
src/commentbot/param_types.jl
src/commentbot/parse_comment.jl
test/server.jl

Relevant: #130
This removes the usage of the Julia parser, adds a modified new syntax for commands, but keeps the old one intact.
Example:
```
@JuliaRegistrator register branch=release-1.0 target=myregistry
```
The only thing lost is the capture of positional arguments in the psuedo-function-call, which we never used anyways.

Update comment trigger to not need to be Julia syntax

---

src/commentbot/parse_comment.jl
test/server.jl

Previously something like this:
```
register(branch="foo")
Some other text
```
Would parse `:branch => "foo)"`.
This is actually a non-issue for the current deploy because the input to the function never contains more than one line, but it's better to not make that assumption.

Properly strip parens for multi-line input

---

src/management.jl
src/webui/routes/register.jl
src/webui/routes/status.jl
src/webui/templates/select.tpl

This improves the current polling situation a little bit. Instead of sending a request every 5 seconds and instantly getting the current status back, the server waits for up to 10 seconds for the registration to finish. If it's still going, the same process begins again.
This means:
- 5x less requests for the client to make
- Faster response from the server, since checks are effectively every second instead of every 5
The timeout is arbitrary, and could probably be a lot longer.
The next logical step would be websockets but that's less trivial.
A couple of other changes were made, basically just code style. I got rid of the `console.log`s since that's frowned upon. Also the results text was changed from red back to default, I thought it a bit strange to see angry-looking text reporting …

WebUI: Use long polling for registration status check

---

src/webui/gitutils.jl

Was using the GitHub `organization.login` attribute rather than the GitLab one.

Fix collaborator check for GitLab

---

src/webui/gitutils.jl

After cloning a repo, remote branches exist as `origin/branchname` but they do not exist locally. Therefore `git show branchname` always fails unless the branch is `master`.
By running `git checkout branchname`, a local branch is created that tracks the remote one.
Illustrated:
```sh
xps [ ~ ] git clone -q git@github.com:JuliaRegistries/Registrator.jl.git Registrator
xps [ ~ ] git -C Registrator show cdg/treesha --format=raw
fatal: ambiguous argument 'cdg/treesha': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
x xps [ ~ ] git -C Registrator checkout cdg/treesha
Branch 'cdg/treesha' set up to track remote branch 'cdg/treesha' from 'origin'.
Switched to a new branch 'cdg/treesha'
xps [ ~ …
```

Correctly get tree SHA when ref is a branch

---

src/Registrator.jl
src/commentbot/CommentBot.jl
src/commentbot/verify_projectfile.jl
src/webui/WebUI.jl
src/webui/gitutils.jl
src/webui/routes/register.jl

[Context](https://discourse.julialang.org/t/status-of-registrator-jl-getting-an-invalid-project-toml-error/25546)
The Base64 stdlib does not properly discard whitespace when decoding. This should probably be fixed there too.

Ignore whitespace in base64 strings

---

src/regedit/utils.jl
test/regedit.jl

Use `Base.version_slug` for branch names, fixes #165, fixes https://github.com/JuliaRegistries/General/issues/1765.

Include part of the UUID in branch names

---

Manifest.toml
Project.toml
src/webui/gitutils.jl
src/webui/routes/register.jl

WebUI: Check for existing tag

---

src/regedit/register.jl

This allows us to register into registries not located in the typical location.

Add pass-through of `cache` for `register()` -> `get_registry()`

---

Project.toml

GitForge will have breaking changes in v0.2 (https://github.com/christopher-dG/GitForge.jl/issues/12)

Restrict GitForge to < 0.2

---

src/regedit/register.jl

This reverts #215, which introduced a bug (see my comment on that PR) that is throwing when I use my rewrite of PkgDev.jl (but it looks like a generic bug to me that should affect others as well).
A speedy merge would be fantastic.
CC @staticfloat

Revert "Copy over https://github.com/JuliaLang/Pkg.jl/pull/1350"

---

src/regedit/get_builtin_pkgs.jl

This is a quality of life improvement for people running Registrator on a system with a user account not called "registrator." It's otherwise equivalent.

Use homedir instead of hard-coding path to home directory

---

README.md

The readme has some links to the documentation but some of them were giving me a 404 error. 
I've tried to update those cases---I used the stable version of the documentation and made a guess as to which page the links should point to.
Also, the very last sentence of the readme was removed since it appeared to be redundant.

Update links to documentation in readme

---

README.md

Add some minimal documentation regarding how the docs for packages will be built. This at least provides a starting point for new people to look to when trying to figure out how packages are added and docs built by Registrator.

Doc gen docs

---

Project.toml
src/commentbot/github_utils.jl

The GitHub Actions token (`GITHUB_TOKEN`) has write permissions on the repo on which the action is installed, and no permissions on other repos.
So, if we see a commit comment inside the `Foo.jl` repository, and the comment is made by the `github-actions[bot]` user, then we know that the comment was made by a GitHub Action installed on the `Foo.jl` repository.
Therefore, I think that we should allow the `github-actions[bot]` user to trigger Registrator.
This pull request allows the `github-actions[bot]` user to trigger Registrator on repos owned by individual users and repos owned by organizations.

Allow GitHub Actions to trigger the Registrator GitHub app

---

src/webui/WebUI.jl

I changed to `stable`; not sure if that should be to `dev` instead like the previous one was to `master`.

Update "Usage" docs link for webui

---

src/commentbot/CommentBot.jl
test/server.jl

This lets us use `@juliaregistrator register` (fixes a gripe mentioned on Slack).

Make trigger phrase case-insensitive

---

src/commentbot/github_utils.jl

`raise_issue` currently takes a `Regex` as its second argument, but the code itself expects a `RegexMatch`, as the code later tries to find the `match` field of `phrase`. This PR simply modifies the method signature so that the method can be matched

Fix raise_issue

---

run/config.commentbot.toml

The inline comments next to some of the options here are confusing as they currently describe the opposite of the behavior specified by the config file.

Negate some comments

---

run/config.commentbot.toml

The approval process needs an email in order to create a tag in the source repo, https://github.com/JuliaRegistries/Registrator.jl/blob/master/src/commentbot/approval.jl#L3
That line is currently missing from the commentbot's config, which leads to an error in the approval call. This PR just adds a line to the config as a prompt to add in the email

Add in email field to commentbot config

---

src/slack.jl

the toplevel file `Registrator.jl` includes `slack.jl` but not `management.jl`, so the function `get_backtrace` which is defined in `management.jl` is not available within the `post_on_slack_channel` function. 
We could of course include the management file first before the `slack.jl` file, but there's a lot of stuff defined in there, so I figured it might be better to just manually inline the `get_backtrace` function into `post_on_slack_channel`

Fix slack backtrace

---

run/config.commentbot.toml
run/config.regservice.toml
run/makefile

Currently, the default config for the commentbot, regservice and webui is to listen for file-creations in the /tmp/ folder, but the default behavior for the make command is to create the stop-files in the working directory. This pr changes the latter to create the files in /tmp/, as expected

Update stop-* make commands to correct file paths

---

Project.toml

I looked at the commits made to master since 1.1.1, and they all seem to me like they are bug fixes or new features.

Bump version from "1.1.1" to "1.2.0"

---

docs/src/webui.md
run/config.commentbot.toml
run/config.regservice.toml
run/config.web.toml
src/RegService.jl
src/commentbot/CommentBot.jl
src/webui/WebUI.jl

So that a custom logger can be used in the calling code.

Add option to disable default logger

---

Project.toml

There has been one commit (a bug fix) merged to master since the last release (1.2.1).
This PR bumps the version to 1.2.2. After it is merged, we can make a new release.

Bump version from "1.2.1" to "1.2.2"

---

src/webui/gitutils.jl

* Dont warn when JuliaProject.toml is missing (which is the case for most packages)
* Log an error when project file is not found.

Change Project file warning to error

---

src/webui/gitutils.jl

`repo.namespace` is always present but `repo.owner` can sometimes be `nothing`

Fix getting repo namespace for GitLab

---

src/webui/gitutils.jl

It seems `git rev-parse <branch-name>:` only works for default branches and checked out branches. For remote branches we need to add `origin/` as a prefix.

Add 'origin/' prefix to branch in git rev-parse

---

src/webui/gitutils.jl

Doing a bare git clone:
* Makes all the remote branches local
* Gives us all the tags
Its also slightly faster than just clone.
This will fix https://github.com/JuliaRegistries/Registrator.jl/issues/339 and also correctly fixes what https://github.com/JuliaRegistries/Registrator.jl/pull/335 tried to fix

Do a bare clone when getting tree SHA

---

Manifest.toml
Project.toml
docs/src/webui.md
run/config.commentbot.toml
run/config.web.toml
src/commentbot/CommentBot.jl
src/commentbot/github_utils.jl
src/webui/WebUI.jl
src/webui/gitutils.jl

Motivation: We would like to use a fork of the registry repo to make registration pull requests. This would allow us to make registration requests without requiring that Registrator have write access to the Registry repo.
Description of changes: Added a new configuration parameter to configure the Registry fork's URL. If this is unspecified it defaults to the clone URL.
Dependencies: https://github.com/JuliaRegistries/RegistryTools.jl/pull/68

Option to push registration commits to a fork of the registry repo

---

README.md

Fixes README link
Correct link is now https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/.

Fix broken link to "automatic merging guidelines"

---

README.md

The existing instructions combine registering and setting up a new package with triggering a new release on an existing one.  While correct, it is a little confusing.
This adds in a simple description of how to trigger a new release in a preexisting package setup with TagBot/etc.

Added instructions for triggering a new release with existing package

---

README.md

Fixes https://github.com/JuliaRegistries/General/issues/66500
Closes https://github.com/JuliaRegistries/Registrator.jl/pull/383

The `JuliaRegistries/Registrator.jl` README should link to the `JuliaRegistries/General` README

---

docs/src/webui.md
src/webui/gitutils.jl

- Change `@gf_q` to `@gf` for a `get_repo` call so that error is logged
- Add docs for allowing third party OAuth access to private repositories on GitHub

Add note for private packages

---

src/webui/WebUI.jl
src/webui/gitutils.jl

The assertion that is removed in this PR has failed recently for a user. The changes in this PR should give more information if such a failure happens again

Change assertion to "if" and log error

---

src/Registrator.jl
src/commentbot/CommentBot.jl
src/commentbot/param_types.jl
src/webui/WebUI.jl
src/webui/gitutils.jl
src/webui/routes/register.jl

~The `istagwrong` method checks whether the commit SHA of the registration ref matches the commit SHA of the corresponding tag (if such a tag exists). This does not work for subdir packages since their versions need not be same as the repo tag. This PR skips the tag check when subdir is non-empty~

Fix WebUI tag check for subdir packages

---

src/commentbot/CommentBot.jl

Untested, but should look something like this:
____
```
@JuliaRegistrator register()
```
____
Registration pull request created: JuliaRegistries/General/xxxx
Did you know you can add release notes too? Just add markdown formatted text underneath the comment and it will be added to the registry PR, and if tagbot is installed it will also be added to the tag created on this repository.
After the above pull request is merged, it is recommended that a tag is created on this repository for the registered package version.
This will be done automatically if the Julia TagBot GitHub Action is installed, or can be done manually through the github interface, or via:
```
git tag -a v1.3.1 -m "<description of version>" 7d4c8c4c918148afc371e4814d1f2929c3f46b37
git push origin v1.3.1
```

Add release notes note if no release notes provided

---

docs/make.jl
src/pull_request.jl

Otherwise `#12345` was being expanded to General PRs not PRs on the origin repo.
The many backticks allows this to work:
`````
```
hello
```
````
world
````
`````

put release notes in a code block to avoid automatic PR links being wrong

---

Project.toml
src/webui/gitutils.jl

Originally added in #358 this was broken in #392. Setting `head` back to `fork_owner:branch` in this PR.

fix: create github pull request for forked registry

---

src/commentbot/CommentBot.jl
src/commentbot/approval.jl
src/management.jl
src/webui/gitutils.jl
src/webui/routes/register.jl

It makes the stacktraces from the error handlers pretty much useless and hinders debugging. In particular, since `exception` is now just a string, the logging macros will elide most of the stacktrace. As an MWE:
```
julia> try
error("1234")
catch e
@error "Error handler" exception = sprint(Base.showerror, e, catch_backtrace())
end
┌ Error: Error handler
│   exception = "1234\nStacktrace:\n  [1] error(s::String)\n    @ Base ./error.jl:35\n  [2] top-level scope\n    @ REPL[9]:2\n  [3] eval\n    @ ./boot.jl:370 [inlined]\n  [4] eval_user_input(ast::Any, backend::REPL.REPLBackend, mod::Module)\n    @ REPL ~/.julia/juliaup/julia-1.9" ⋯ 974 bytes ⋯ "816 [inlined]\n [12] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)\n    @ Base ./client.jl:405\n …
```

Don't use the `exception=get_backtrace(...)` pattern

---

Project.toml
src/webui/gitutils.jl

Broken by #431. `get_pull_requests` requires head to be mentioned in the format `$owner:$branch` always.
With just `branch` it retrieves all pull requests, Example:
```
Error: Expected to find one open pull request created from a previous registration attempt but got 30 pull requests
```

fix: head is incorrect for get_pull_requests

---

Project.toml
src/webui/gitutils.jl

use GIT_ASKPASS to hide token from log messages

feat: use GIT_ASKPASS with git clone so tokens do not appear in log messages

---

test/webui/gitutils.jl

Add more path traversal tests.
Ref: https://github.com/JuliaRegistries/Registrator.jl/pull/449#discussion_r2148838047

add more tests for cloneurl valid pattern

---

Project.toml

We need HTTP v1.10.17 in order to get https://github.com/JuliaWeb/HTTP.jl/pull/1225, which in turn gives us https://github.com/JuliaWeb/URIs.jl/pull/66.
And we need URIs v1.6 in order to get https://github.com/JuliaWeb/URIs.jl/pull/66.
And we need GitForge.jl v0.4.3 in order to get https://github.com/JuliaWeb/GitForge.jl/pull/50.

Require HTTP.jl v1.10.17, URIs v1.6, and GitForge.jl v0.4.3
