- Manifest.toml
- Project.toml
- src/Server.jl
Have a look. No tests, but a pretty simple fix. Hope it is alright 🙏
> Remove DataStructures dependency

- src/Server.jl
Pattern accepted now: @JuliaRegistrator `register(...)`.
JuliaRegistrator is the GitHub account hosting the registrator app.
optional keyword args for `register`:
- branch: a branch to register (valid only on an issue comment)
- target: a specific registry to target (default is all registries configured with the app). e.g. `register(target=General)` or `register(target=Pro)`
fixes #17
> update comment listener trigger format

- src/register.jl
> cleanup stale registry on failure

- src/register.jl
Version specifier in compat section of Project.toml is now expanded.
fixes #19
> expand version specifier in compat

- src/register.jl
Add a comment to originating repo when package name change is detected (instead of creating an issue in Registrator.jl)
fixes #16
> nicer error msg when package name is changed

- README.md
I have tried to make backticks directly visible, reordered the beginning slightly so that the intro sentence comes first, and added a sentence about that the maintainer of the registry has to approve the PR.
> Small clarifications

- src/register.jl
This adds an argument to `register` to add additional registries in which to look up packages for UUID verification. This is the only place where these registries are used, and this appears to be the only missing piece to allow cross-registry dependencies to be recorded using `register`.
EDIT: Closes #53
> Allow package dependencies to be found in additional registries

- README.md
- full_readme.md
- src/Server.jl
* Update README.md
* Remove necessity of back-tick
* Respond with git tag command
* Check and don't allow pre-release version
> Bunch of fixes for release

- src/Server.jl
- src/register.jl
> Check for existing version, warn for Base.check_new_version errors

- image/Dockerfile
@nkottary Using this line in the Docker file fixes #71 when the user is trying to deploy to Heroku.
> Add GIT installation command to Dockerfile

- src/register.jl
> Borrow code from Base.check_new_version

- src/Server.jl
> Update PR body format for TagBot compatibility

- README.md
It wasn't obvious to me how to set the version in a new release. This adds a sentence about this, at least as I understand it.
> Mention setting a version in README

- src/regedit/register.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/1155.
> fix VersionSpec printing in Compat.toml

- Manifest.toml
- Project.toml
- src/Registrator.jl
- src/regedit/RegEdit.jl
- src/regedit/register.jl
- src/regedit/utils.jl
See https://github.com/JuliaComputing/Registrator.jl/pull/92#issuecomment-484609860
> Revert "Misc TOML writing changes"

- src/Server.jl
- src/regedit/register.jl
> Say new package or version in PR title

- src/regedit/register.jl
Code copied from https://github.com/JuliaLang/Pkg.jl/pull/1163
> A better compress_versions

- src/regedit/register.jl
Fixes https://github.com/JuliaComputing/Registrator.jl/issues/114.
> monkey patch Pkg.Types.compress_versions

- src/Server.jl
Fixes #108 
Fixes https://github.com/christopher-dG/tag-bot/issues/3 (am I allowed to do this?!)
I haven't tested this, maybe someone more familiar with test-deploying Registrator and using GitHub.jl can tell me if this is going to break or not.
> Update PR body when it already exists

- src/regedit/register.jl
> Check [extras] when determining version compatibility

- src/regedit/register.jl
> Fix displaying Registrator commit when it is installed with Pkg.add

- src/Server.jl
- test/webui.jl
fixes https://github.com/fredrikekre/jlpkg/commit/4797913f41002874c3b4649e8f83e17792de9e8c#commitcomment-33418965
Edit: better view of diff: https://github.com/JuliaRegistries/Registrator.jl/pull/131/files?w=1
> Remove restriction that repos must end with .jl.

- src/regedit/register.jl
> Move compress and save methods from Pkg to avoid warnings

- src/WebUI.jl
> Add missing JSON import, fix RegBranch error access

- README.web.md
- run/config.web.toml
- src/commentbot/CommentBot.jl
- src/commentbot/param_types.jl
- src/pull_request.jl
- src/webui/WebUI.jl
- src/webui/routes/select.jl
Related: https://github.com/JuliaRegistries/General/pull/781#issuecomment-492781761 and https://github.com/JuliaRegistries/TagBot/pull/17
> Quote patch notes, rename patch notes -> release notes

- README.web.md
- run/config.commentbot.toml
- run/config.regservice.toml
- run/config.toml
- run/config.web.toml
- src/Messaging.jl
- src/RegService.jl
- src/commentbot/CommentBot.jl
- src/webui/WebUI.jl
* Fix `trigger` doc in config file
* Make backend port configurable
* Have separate config files for RegService and CommentBot
> Some config changes

- README.md
> mention release notes are automatically generated

- README.md
Confused me in https://github.com/JuliaGeo/NetCDF.jl/commit/0f492e0c900b55fee3fac7183fc30cd0f31885aa
> README: use register() instead of register

- README.md
Reverts JuliaRegistries/Registrator.jl#170
Reverting because latest of master is live now.
> Revert "README: use register() instead of register"

- src/webui/routes/index.jl
- src/webui/templates/index.tpl
- src/webui/templates/select.tpl
> UI Enhancement

- Manifest.toml
- src/regedit/register.jl
>  Fix error reporting for compat errors 

- README.md
> Mention web interface in usage instructions

- .codecov.yml
Feel free to disagree, but I get no value from the comments it makes, and code coverage on this project seems to not be a priority in any case.
> Disable Codecov comments

- src/commentbot/CommentBot.jl
- src/commentbot/param_types.jl
- src/commentbot/verify_projectfile.jl
- src/webui/routes/register.jl
> CommentBot: Check for existing tag before registering

- src/commentbot/CommentBot.jl
- src/commentbot/github_utils.jl
- src/commentbot/param_types.jl
- src/webui/gitutils.jl
- src/webui/routes/register.jl
> Allow registration when existing tag is correct

- src/regedit/register.jl
- src/regedit/types.jl
These pieces of functionality are really useful for the next version of BB
> Allow specifying `branch` name, and whether to reset the registry every time

- src/webui/gitutils.jl
Was broken by 508c3c920dee43ed36f173bfaa940d3440b10861
> Fix authorization check

- docs/make.jl
- docs/src/commentbot.md
~~I'll relocate this to the docs/ directory once #226 lands.~~ Done
> Add a document for the comment bot setup

- src/commentbot/param_types.jl
- Change "Please trying" to "Please try"
- Reword sentence to provide a more natural reading flow
> Improve disable_pull_request_trigger error message

- src/regedit/register.jl
> Show invalid entries in [compat] together

- src/commentbot/approval.jl
Hi,
I've been running into an issue recently where the approval process on a custom version of Registrator will error when there are no existing tags for the repository from which the original registration event originated. The code works just fine if there is an original tag.
An alternative fix is to perhaps call `tags` with the `handle_error=false` option, though I haven't tried that locally. Happy to modify this PR to use that option if it's preferable, let me know!
> Handle case where no tags exists in approval process

- src/webui/WebUI.jl
- src/webui/gitutils.jl
- src/webui/routes/register.jl
- test/webui.jl
> Added support for ssh addresses.

- src/webui/gitutils.jl
- src/webui/routes/register.jl
The old method does not work for tags
> Fix for tagged registration for GitHub

- src/commentbot/github_utils.jl
- src/commentbot/param_types.jl
> Use default branch in Comment Bot

- README.md
Clearly document adding the bot to a repository
> Clearly document adding the bot to a repository

- src/commentbot/CommentBot.jl
This allows keyword arguments to be specified while launching commentbot which would be passed on to the GitHub.jl event listener.
Helps specify additional options via API while starting the server.
> let CommentBot pass keyword args to event listener

- src/webui/gitutils.jl
See https://github.com/JuliaRegistries/Registrator.jl/issues/343 and https://github.com/JuliaRegistries/Registrator.jl/commit/1c35395182bed76b294acbefb426cc0d238efed1
> Remove isdir check for sub-directory in gettreesha

- src/webui/WebUI.jl
- src/webui/routes/register.jl
> passing subdirectory to RegistryTools

- Project.toml
- src/commentbot/github_utils.jl
Requires https://github.com/JuliaWeb/GitHub.jl/pull/189 (~~will leave this PR in draft until that functionality is in a release so I can update the compat here~~ done).
Fixes #308
> Only remove labels we've added

- Manifest.toml
Direct dependencies:
```
[8f6bce27] ↑ GitForge v0.1.6 ⇒ v0.1.7
[bc5e4493] ↑ GitHub v5.1.8 ⇒ v5.7.0
[cd3eb016] ↑ HTTP v0.8.19 ⇒ v0.9.17
[682c06a0] ↑ JSON v0.21.1 ⇒ v0.21.2
[78c3b35d] ↑ Mocking v0.7.1 ⇒ v0.7.3
[ffc61752] ↑ Mustache v1.0.8 ⇒ v1.0.12
[a975b10e] ↑ Mux v0.7.3 ⇒ v0.7.6
[d1eb7eb1] ↑ RegistryTools v1.5.3 ⇒ v1.6.0
```
All dependencies:
```
[34da2185] + Compat v3.40.0
[9a962f9c] ↑ DataAPI v1.4.0 ⇒ v1.9.0
[e2ba6199] ↑ ExprTools v0.1.3 ⇒ v0.1.6
[8f6bce27] ↑ GitForge v0.1.6 ⇒ v0.1.7
[bc5e4493] ↑ GitHub v5.1.8 ⇒ v5.7.0
[cd3eb016] ↑ HTTP v0.8.19 ⇒ v0.9.17
[692b3bcd] ↑ JLLWrappers v1.1.3 ⇒ v1.3.0
[682c06a0] ↑ JSON v0.21.1 ⇒ v0.21.2
[2535ab7d] ↑ JSON2 v0.3.2 ⇒ v0.3.4
[50d2b5c4] - Lazy v0.15.1
[1914dd2f] ↑ MacroTools v0.5.6 ⇒ v0.5.9
[78c3b35d] ↑ Mocking v0.7.1 ⇒ v0.7.3
[ffc61752] ↑ Mustache …
```
> Update the `/Manifest.toml` file

- src/commentbot/verify_projectfile.jl
Catch and report error from `Pkg.Types.read_project`. Ref: https://github.com/JuliaRegistries/General/issues/58372#issuecomment-1096138969
> Catch and display read_project error

- Manifest.toml
- Project.toml
RegistryTools.jl v1.8 changes the PR branch name, see https://github.com/JuliaRegistries/RegistryTools.jl/pull/63 and https://github.com/JuliaRegistries/RegistryTools.jl/pull/71
> Update RegistryTools to 1.8, update Registrator version to 1.4

- .github/workflows/CompatHelper.yml
Update to the latest recommended CompatHelper configuration from upstream: https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml
> Update to the latest recommended CompatHelper configuration

- Manifest.toml
> Re-resolve and update the `Manifest.toml` file; continue using Julia 1.7.2 for the manifest file

- Manifest.toml
- Project.toml
- run/config.web.toml
- run/regservice.sh
- run/webui.sh
- src/webui/WebUI.jl
- src/webui/gitutils.jl
- src/webui/providers.jl
- src/webui/routes/auth.jl
- src/webui/routes/bitbucket.jl
- src/webui/routes/callback.jl
- src/webui/routes/index.jl
- src/webui/webutils.jl
- test/runtests.jl
- test/webui.jl
- test/webui/gitutils.jl
This PR adds support for Bitbucket, as well as some source documentation and refactoring needed for Bitbucket support -- Bitbucket diverges from many of the similarities between GitHub and GitLab.
> Support Bitbucket

- src/commentbot/github_utils.jl
- src/management.jl
- src/webui/WebUI.jl
- src/webui/gitutils.jl
- src/webui/webutils.jl
- UndefVarError for `mention` in comment bot
- lowercased provider in callback.jl so that provider can be found in config file
> Fix some regressions

- Project.toml
> Registrator.jl 1.8.0

- Project.toml
> Registrator.jl 1.9.0

- src/commentbot/CommentBot.jl
issue reported on Slack: https://julialang.slack.com/archives/C6M4DQA5P/p1736027749028509
followup to https://github.com/JuliaRegistries/Registrator.jl/pull/439
> Fix linebreaks in CommentBot message
